language: python
python:
  - "3.6"

install:
  - pip install getpass
  - pip install smtplib
  - pip install MIMEText
  - pip install MIMEMultipart
  - pip install coala
  - pip install coala-bears

script:
  - echo "skipping tests"
  - coala --non-interactive
